### ISSUE TITLE
Bug with Creating a Table using HTML code

### ISSUE THREAD

**Issue by Anu-S** [DevopediaOrg/webapp#121]
want to highlight the difference between two python version 2 and 3
Not able to create a table using HTML code and there is no support in our page to create a table.

sample code which i used to create a table
<table>
  <tr>
    <th>**Python 2.X**</th>
    <th>**Python 3.X**</th>
  </tr>  
  <tr>
    <td>print is a statement</td>
    <td>print() is a built-in function</td>
  </tr>   
  <tr>
<table>

using the above code able to create table without border. but to create a border using <style> is not supported.

**Comment by arvindpdmn** [comment]
Style will not be supported due to security reasons and to preserve consistent look and feel. But table will be supported in next release.

**Comment by arvindpdmn** [comment]
Done.
