### ISSUE TITLE
Main search box default text missing

### ISSUE THREAD

**Issue by arvindpdmn** [DevopediaOrg/webapp#3]
The same happens in menu search box. It works in offcanvas.

**Comment by arvindpdmn** [comment]
Not really sure if this is needed. Google doesn't have a default text on its search box.

**Comment by santoshvh** [comment]
We should have default text or placeholder.

**Comment by arvindpdmn** [comment]
Google doesn't have placeholder because the cursor is focused on the search box. But focusing the cursor on search box using jQuery's focus() or HTML's autofocus removes keyup and keydown events bound to the search box! Placeholder is present in the <input> tag but is not seen on browser.

No solution as of now. Postponing the fix.

**Comment by arvindpdmn** [comment]
In offcanvas mode, although default text "Search..." appears, there's no associated AJAX here. Hence user is not prompted to with matches when he types a few characters. Also, the "Search..." font color must be changed to something lighter: rgba(98, 98, 98, 0.5);

Any fix should preserve the AJAX behaviour.

**Comment by arvindpdmn** [comment]
Related to #155

**Comment by arvindpdmn** [comment]
Done
