### ISSUE TITLE
Autodownload and autogen media caption for source attribution

### ISSUE THREAD

**Issue by arvindpdmn** [DevopediaOrg/webapp#32]
With this feature, when media is specified via an external URL, Devopedia should automatically download the media, check its validity, and update the article. Caption will also be automatic.

Old files of that article should be deleted since we will not version media.

**Comment by arvindpdmn** [comment]
This task is probably a security threat. If the link points to a large image or video, it will hog data transfer resources. If it points to a malicious URL, that could cause problems as well. It's better to ask users to upload.

Are there cases where it's not possible to figure out the type or size of download without actually downloading the file? Such a thing would be a security threat.

**Comment by arvindpdmn** [comment]
Done.

**Comment by TimeBandit** [comment]
Yes it is security threat. I found the following ways of protection [here](http://bit.ly/2kgNuvI):
**Defending against file upload attacks**
**There are six steps to protecting a website from file-upload attacks.**
- The application should use a whitelist of allowed file types. This list determines the types of files that can be uploaded, and rejects all files that do not match approved types.
- The application should use client- or server-side input validation to ensure evasion techniques have not been used to bypass the whitelist filter. These evasion techniques could include appending a second file type to the file name (e.g. image.jpg.php) or using trailing space or dots in the file name.
-  The application should set a maximum length for the file name, and a maximum size for the file itself.
-  The directory to which files are uploaded should be outside of the website root.
    All uploaded files should be scanned by antivirus software before they are opened.
-  The application should not use the file name supplied by the user. Instead, the uploaded file should be renamed according to a predetermined convention.

Main thing I am reading is that you should do a virus scan server side before accepting a file.

**Comment by TimeBandit** [comment]
I think that initially you can probably put this on the back burner as it's going to slow you down but you could probably place a mock virus checking function in your server code to fill out at a later point.

If you didn't download the file but instead placed the URL into the page document that would probably work for now.

**Comment by arvindpdmn** [comment]
Thx. Currently article has only URL pointing to external sites but in v0.3, file upload function will be available. File upload is a necessary feature because for example authors could create an original image and hence they can't actually point to a URL. Will implement all the checks noted above (a very useful list) but have to think about how to do virus scan.

This bug is about downloading automatically given the URL. It's really to make things easier for authors. I suppose the same checks could be applied as in a file upload. Reopening the bug but maybe not for v0.3.

**Comment by arvindpdmn** [comment]
Won't fix.
