### ISSUE TITLE
CSS animation on milestones

### ISSUE THREAD

**Issue by arvindpdmn** [DevopediaOrg/webapp#36]
Milestones should slide in from the right.

**Comment by arvindpdmn** [comment]
Current implementation was adapted from https://webdesign.tutsplus.com/tutorials/building-a-vertical-timeline-with-css-and-a-touch-of-javascript--cms-26528

This source has animation but it doesn't work when timeline takes only part of the screen's width.

**Comment by TimeBandit** [comment]
How do I view this? I could do it on the weekend but will try to look at it before then

**Comment by arvindpdmn** [comment]
Once you create a full article with milestones, you will be able to see it. I might create a full article tomorrow. Anyway, it's not urgent.

**Comment by arvindpdmn** [comment]
Done.
