### ISSUE TITLE
Homepage navbar should reflect login status

### ISSUE THREAD

**Issue by TimeBandit** [DevopediaOrg/webapp#37]
After registering via linkedIn and returning to the homepage the navbar still display 'LOGIN'. If the user is logged in then the navbar should reflect this. Suggest replacing the text with 'SETTINGS' or 'MY ACCOUNT' or a profile picture.
//
![screenshot from 2017-01-22 11-30-42](https://cloud.githubusercontent.com/assets/2059850/22182178/944ca0ec-e096-11e6-960f-c381912b589d.png)

**Comment by arvindpdmn** [comment]
Yes, this is linked to another bug because the current header is not very responsive. #2

**Comment by arvindpdmn** [comment]
Using icons rather than text. Sign-in icon changes to user icon after logging in.
