### ISSUE TITLE
Cant find article created

### ISSUE THREAD

**Issue by TimeBandit** [DevopediaOrg/webapp#43]
I wrote a test article on JavaScript. Now I have no where of finding it. Typing 'JavaScript' into the searchbar yields results which yield nothing.

**Comment by arvindpdmn** [comment]
Closing. See it on the Dashboard. Click on Dashboard itself, not on the sub-menu that opens up. This behaviour is likely to change.

**Comment by TimeBandit** [comment]
Ok I see, with fresh eyes I assumed that 'DASHBOARD' was just a menu header when the menu dropped below it, not a link that would take me somewhere. If you want to leave 'DASHBOARD' on the navbar then perhaps it could be re-worded to 'MY DASHBOARD' and/or the dashboard page itself could have the 'add new' and 'guidlines'
