### ISSUE TITLE
Feature Request: do not display canvas on mobile 

### ISSUE THREAD

**Issue by TimeBandit** [DevopediaOrg/webapp#46]
Suggest you disable the canvas on mobile as the animation does not look as good as it does on desktop. It also run slowly so is probably using resources unnecessarily. 
![photo](https://cloud.githubusercontent.com/assets/2059850/22182400/8c4bc6e2-e09c-11e6-9c0e-870d2d47f7cd.PNG)

**Comment by arvindpdmn** [comment]
Need to test at my end. Marked as a bug.

**Comment by arvindpdmn** [comment]
Just tested. It is slow on a Galaxy S4 as well. It's a good idea to keep it light and remove it altogether. In future, we may have a static image or an animated GIF to celebrate important days the way Google does it with its doodles.
