### ISSUE TITLE
Search bar displays near the bottom on mobile

### ISSUE THREAD

**Issue by TimeBandit** [DevopediaOrg/webapp#48]
Suggest you move the search bar to below that navbar and make it full width
![photo](https://cloud.githubusercontent.com/assets/2059850/22182463/7f1bdb28-e09d-11e6-98bc-f850bedb54e4.PNG)

**Comment by arvindpdmn** [comment]
This varies. Please specify the phone model.

**Comment by TimeBandit** [comment]
Iphone 4

**Comment by arvindpdmn** [comment]
3.5 inches (~54.0% screen-to-body ratio)
640 x 960 pixels (~330 ppi pixel density)

Strange. I don't have iPhone but on Firefox it's showing okay. See screenshot.

![screenshot-ff-iphone4](https://cloud.githubusercontent.com/assets/5135463/22183049/7c8542fe-e0da-11e6-9390-f4a8174acc30.png)

**Comment by TimeBandit** [comment]
I have seen the same misleading results, real world is different :p

**Comment by arvindpdmn** [comment]
Managed to test this on iPhone5 yesterday. Problem is confirmed. It has to do with viewport dimensions in CSS.

**Comment by arvindpdmn** [comment]
Done.
