### ISSUE TITLE
[UI Bug] Hyperlink icon to other webpages are way to small to be clickable

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#519]
![image](https://user-images.githubusercontent.com/26280748/111274652-44d6b600-865b-11eb-9be1-6043f4a77f3c.png)
The * symbol which is being shown for the hyperlinks are way too small to be clickable, when I try to click on it, it takes around 3-4 seconds to correctly position pointer on hover. Can we use better design than this? For e.g. using anchor tag with the text itself rather than * character.

**Comment by arvindpdmn** [comment]
Very grateful for your time and effort in recording so many useful observations (in other issues here on GitHub).

Would like more insight on this particular problem. Are you doing this on mobile or desktop? We can increase the size but we would also like it to be unintrusive for design reasons. We'll see what can be done.

**Comment by arvindpdmn** [comment]
Not fixing for the above reasons.
