### ISSUE TITLE
[bug] Create an hyperlink for chats at the end of page.

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#521]
![image](https://user-images.githubusercontent.com/26280748/111283276-f4fcec80-8664-11eb-8948-718e3fec7ed8.png)
In the article stat you show there are 4 comments in chat, but also provide a way to interact with the chat by opening a chat window similar to what you do by clicking on chat icon in right rail.
![image](https://user-images.githubusercontent.com/26280748/111283412-19f15f80-8665-11eb-853e-6032ddf095ad.png)

**Comment by arvindpdmn** [comment]
Very interesting. Scheduling this for next release. In fact, this can be expanded to Edits as well.

**Comment by arvindpdmn** [comment]
Done
