### ISSUE TITLE
Bad UI when clicked upon edit the article.

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#523]
![image](https://user-images.githubusercontent.com/26280748/111285735-73f32480-8667-11eb-9b1b-9b984d7ee3df.png)

2 issues:

1. These text boxes by default are way too smaller, only when you click inside the box it becomes larger. Make it large by default. 
2. Why is this time info box floating on the page. Only when I navigated to the top of page I realised this is the time require to publish the article. either remove it or find a better design alternative.

**Comment by arvindpdmn** [comment]
- Box size: interesting but none of our authors have complained about this. Need to check with them.
- We want the time to be always visible and obvious to the author. Unable to find a better design for now. So far no complaints from our regular authors.

**Comment by arvindpdmn** [comment]
No action for now.
