### ISSUE TITLE
For edit this article page, provide an option to close the text box appearing as help.

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#524]
![image](https://user-images.githubusercontent.com/26280748/111290794-8328a100-866c-11eb-86a0-9959233c4fb7.png)

If a user wants to close the text box once he is done reading, there is no option provided for that functionality.

**Comment by arvindpdmn** [comment]
Yes, we realized this but was never a top priority since none of our authors complained about this. In any case, it's a good time to schedule it now since it's a small code change. Scheduling for next release.

**Comment by arvindpdmn** [comment]
Done
