### ISSUE TITLE
[Enhancement] Provide an option for custom request for articles rather than just 6 options on homepage.

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#525]
Right now in homepage for devopedia, only 6 options for request for articles are available. Please provide a way to submit custom request as well based on tags or whatever way you prefer.

![image](https://user-images.githubusercontent.com/26280748/111293514-5b870800-866f-11eb-8a08-77b1d24c37db.png)

**Comment by arvindpdmn** [comment]
No, we don't have this option and don't intend to provide this. If someone has an article in mind, we want to encourage them to start writing the article instead of requesting for it.

However, visitors can vote for requested articles at https://devopedia.org/site-map/faq-help?requested-articles
