### ISSUE TITLE
Change version/section selection in chat: Firefox hover problem

### ISSUE THREAD

**Issue by arvindpdmn** [DevopediaOrg/webapp#71]
Problem seen only in Firefox. Okay in Chrome and Edge. When hovering on another option (without clicking), selected text changes to the hovered value. This affects the list of chat messages displayed.

**Comment by arvindpdmn** [comment]
Problem is seen when using jQuery or direct DOM.

**Comment by TimeBandit** [comment]
Would be nice to know how to reproduce or see a screenshot. However if this is browser specific then you need a DOM library that has browser specific fail-safes and not be using vanilla JS. Use JQuery.

**Comment by arvindpdmn** [comment]
JQuery doesn't work. Neither does DOM. It's the way Firefox implements it!

**Comment by arvindpdmn** [comment]
Not seen in Firefox 71.0 (64-bit) on Windows 10.
