### ISSUE TITLE
registration process password check could be faster

### ISSUE THREAD

**Issue by TimeBandit** [DevopediaOrg/webapp#76]
suggest client side password match and format checking using js. it would save finding out that there is an error after pressing submit. it would be better done by executing the check, client side when the password field loses focus

**Comment by arvindpdmn** [comment]
Yes, requires extra work. Keep in view for later. Server-side check is mandatory in any case and hence it was implemented as a priority.

**Comment by arvindpdmn** [comment]
Done.
